# Generated by Django 4.2.1 on 2023-06-01 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_modified_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='Longitude',
            new_name='longitude',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Vendor'), (2, 'Customer')], null=True),
        ),
    ]
