# Generated by Django 4.2.1 on 2023-06-29 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Received', 'Received'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Processing', 'Processing')], default='Received', max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Received', 'Received'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Processing', 'Processing')], max_length=15),
        ),
    ]
