# Generated by Django 4.2.1 on 2023-06-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_total_data_order_vendors_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_data',
            field=models.JSONField(blank=True, help_text="Data format: {'vendor_id':{'subtotal':'tax_data'}}]", null=True),
        ),
    ]
